### ISSUE TITLE
I think there's something up with HTTP calls

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3996]

**Comment by pbiggar** [comment]
One error is "Error while copying content to a stream.". That occurs in two customer canvases (the canvas from #3983, and another one I'd looked at suspiciously before).

We are getting the same error in our tests (#3564).

It does look a little suspicious, so I'm going to add even more debugging info (this time stack traces).

**Comment by pbiggar** [comment]
Possible clue: https://github.com/dotnet/runtime/issues/23870

**Comment by pbiggar** [comment]
I can get it to fail occasionally locally, by running it in a loop.

```
exception: error: Error while copying content to a stream.
exception: exceptionType: System.Net.Http.HttpRequestException
exception:    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BackendOnlyStdLib.LegacyBaseHttpClient.makeHttpCall@322-24.Invoke(Unit unitVar0) in /home/dark/app/fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs:line 322
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
exception: help_link:
innerException: error: The request was aborted.
innerException: exceptionType: System.IO.IOException
innerException:    at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(HttpResponseMessage responseMessage, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
innerException: help_link:
```

**Comment by pbiggar** [comment]
Thought it might be the proxy: doesn't seem like it

**Comment by pbiggar** [comment]
.@StachuDotNet found a promising lead: it seems I'm using httpclient incorrectly, using `use!` where I should maybe be using `let!`.

This makes me think of the "fixes" I made to pusher recently, which was also seeing a similar problem to this.

**Comment by pbiggar** [comment]
OK, the issue happened again, with both `use!` replaced with a let. Also, it seems that [HttpRequestMessage](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage?view=net-6.0) is an `IDisposible`, so it feels like it's probably correct to use `use!` there.

Or should it be `use`? I'll check that.

Also, there's a few other uses of `use` that I'll check out.

**Comment by pbiggar** [comment]
Hmmm, the `task` CEs I'm using are from Ply - which doesn't use the new F# fancy state machine stuff - possibly it has a different sense of lifetimes.

**Comment by pbiggar** [comment]
I searched for errors in production and in the last 2 hours, they were all socks proxy related.

```
   at System.Net.Http.HttpConnectionPool.EstablishSocksTunnel(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BackendOnlyStdLib.HttpClient.httpCall'@207-15.Invoke(Unit unitVar0) in /home/dark/app/fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs:line 207
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
```

Inner stack trace:

```
   at System.Net.Http.SocksHelper.ReadToFillAsync(Stream stream, Memory`1 buffer, Boolean async)
   at System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync(Stream stream, String host, Int32 port, Uri proxyUri, NetworkCredential credentials, Boolean async)
   at System.Net.Http.SocksHelper.EstablishSocksTunnelAsync(Stream stream, String host, Int32 port, Uri proxyUri, ICredentials proxyCredentials, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishSocksTunnel(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
```

**Comment by pbiggar** [comment]
The logs from the socks proxy look like this:

```
+ su tunnel -c 'ssh -tt -D *:1080 localhost sleep infinity'
channel 9: open failed: connect failed: Name or service not known
channel 21: open failed: connect failed: Name or service not known
channel 24: open failed: connect failed: Name or service not known
channel 9: open failed: connect failed: Connection refused
channel 19: open failed: connect failed: Connection timed out
channel 47: open failed: connect failed: Name or service not known
channel 39: open failed: connect failed: Connection timed out
channel 10: open failed: connect failed: Name or service not known
channel 19: open failed: connect failed: Connection timed out
channel 9: open failed: connect failed: Name or service not known
channel 7: open failed: connect failed: Connection timed out
channel 9: open failed: connect failed: Name or service not known
channel 21: open failed: connect failed: Name or service not known
channel 26: open failed: connect failed: Name or service not known
channel 30: open failed: connect failed: Name or service not known
channel 18: open failed: connect failed: Name or service not known
channel 32: open failed: connect failed: Name or service not known
channel 16: open failed: connect failed: Connection timed out
channel 18: open failed: connect failed: Name or service not known
channel 21: open failed: connect failed: Name or service not known
channel 5: open failed: connect failed: Connection timed out
channel 27: open failed: connect failed: Name or service not known
channel 17: open failed: connect failed: Name or service not known
channel 24: open failed: connect failed: Name or service not known
channel 10: open failed: connect failed: Connection timed out
channel 8: open failed: connect failed: Name or service not known
channel 35: open failed: connect failed: Name or service not known
channel 8: open failed: connect failed: Connection timed out
channel 18: open failed: connect failed: Name or service not known
channel 29: open failed: connect failed: Connection timed out
channel 9: open failed: connect failed: Name or service not known
channel 34: open failed: connect failed: Connection timed out
channel 11: open failed: connect failed: Name or service not known
channel 19: open failed: connect failed: Name or service not known
channel 16: open failed: connect failed: Connection timed out
```

**Comment by pbiggar** [comment]
I think there are other issues too. Going to keep looking. The socks proxy issue wouldn't explain the test failures.

**Comment by pbiggar** [comment]
A place to start tomorrow: are these new issues or did they always exist?

If they are new, then we probably need to report them as issues in dotnet/runtime.

If they always existed, then what did the ocaml client do to paper over these?

Also, is there a better socks proxy or is there something weird going on with DNS or something over there.

Also, do we actually have a status code?

Might want to split this into 2 bugs: socks proxy and other.

**Comment by pbiggar** [comment]
I tested a few of the urls with and without the socks proxy. It seems that all of these urls either don't work or require authentication.

With the socks proxy, I get errors like `<ErrorRail: Error "The request was aborted. The response ended prematurely.">

Without the socks proxy I get errors like: `<ErrorRail: Error "Name or service not known (the.customer.url.com:443) Name or service not known">`

So the issue here is that the sites don't exist, and we're giving bad errors to users.

**Comment by pbiggar** [comment]
I moved the socks stuff to #4005.

**Comment by pbiggar** [comment]
So that just leaves unit tests, which seem to be different from all other cases.
