### ISSUE TITLE
"Blazor worker failed" rollbars

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4099]
https://rollbar.com/darkops/darklang/items/3040/occurrences/233272792330/

**Comment by StachuDotNet** [comment]
`no serialized editor`

The only two places with this text in our code seem to be related to user settings, either saving or loading them:
- https://github.com/darklang/dark/blob/8b481ffb3ff50716e2f3f3ae421769fea89c0a5d/client/src/app/SavedSettings.res#L46
- https://github.com/darklang/dark/blob/8b481ffb3ff50716e2f3f3ae421769fea89c0a5d/client/src/app/SavedUserSettings.res#L17

**Comment by StachuDotNet** [comment]
Thinking again, maybe all of these message are irrelevant to the actual Blazor worker failure; focusing on improving error messaging.

**Comment by StachuDotNet** [comment]
> Looks like it happened many (120) times, by one user, about 40mins ago.

FWIW, it seems these were all within a 3s window.

**Comment by StachuDotNet** [comment]
All blazorworker errors coming from Wasm.fs should have the form `exception: {e.Message}, metdata: {metadata}`, but these don't. Harder to get a good grasp of, but I suspect I can change things in BlazorWorker to improve error reporting.

**Comment by StachuDotNet** [comment]
After adjusting wasm.fs and blazorworker a bit,
and intentinoally throwing an error in Wasm.fs, I've found our `self.onerror` in `BlazorWorker` to be uncalled (at least in some cases) when the error occurs. This is where we expect all Wasm.fs errors to report to, so that's bad. See here: https://github.com/darklang/dark/blob/6bd28512ebd5d276eb8a73df54affba7ef9b5e27/fsharp-backend/src/Wasm/static/BlazorWorker.js#L933

**Comment by StachuDotNet** [comment]
Maybe my changes to our F#'s "self.postMessage" messed something up? Will revert and see.

**Comment by StachuDotNet** [comment]
For all I know these could all be this issue:
![image](https://user-images.githubusercontent.com/906686/172375165-88e383ab-b020-41e7-95ec-037e5b5ba4f2.png)
which is what inspired this investigation. Until I get this information into rollbar or repro locally, though, focusing on improving error-reporting seems best.

**Comment by pbiggar** [comment]
> * "no serialized editor undefined" seems to be the most popular
> * "Rollbar: Recover: Got None but expected something: could not find fluid-editor" paired with "Recover: Got None but expected something: could not find fluid-editor" also present
> * others remain cryptic, with no useful error message as far as I can see

I think these are logs, which is to say recent console messages before the error. I think they're mostly unrelated.

**Comment by StachuDotNet** [comment]
Yeah I figured, since.
Which is why in #4101, I put the console.error before the rollbar - so it's in the logs? Might come in handy.

Feeling a bit stuck until that's merged, as I've no idea how to replicate, and somehow haven't seen self.onError hit locally.

**Comment by StachuDotNet** [comment]
Somehow this error hasn't been seen in prod in the last 4hrs, since #4101. As soon as I threatened to log more, the bug stops? Figures. Hopefully this comment causes the bug to come back out of spite?

**Comment by StachuDotNet** [comment]
got one:

> "Uncaught exception Blazor worker failure Script error. undefined undefined undefined"

:thinking:

**Comment by StachuDotNet** [comment]
`"Uncaught exception Uncaught Error: System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, key\n   at System.Collections.Generic.Dictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Remove(Object )\n   at System.Runtime.InteropServices.JavaScript.Runtime.ReleaseJSOwnedObjectByGCHandle(Int32 gcHandle) https://static.darklang.com/blazor/dotnet.6.0.5.epfcsc29vy-8489de81188395b4e3b672322450c5c20aa22741fe0e93db09b30a011a1984dc.js 1 178397 null"`

another one.

The `ReleaseJSOwnedObjectByGCHandle` looks familiar. I'm starting to think that we shouldn't risk using _any_ kind of `task{}` in the Wasm project, at any level. Doing a quick spike to see how painful that'd be.

**Comment by StachuDotNet** [comment]
Yeah, here's a place where I noted it: https://github.com/darklang/dark/issues/4059#issuecomment-1144856515

Again, trying to see about removing `task{}` altogether, under the assumption we're hitting bad fake-task management.

**Comment by StachuDotNet** [comment]
another idea, maybe terrible, is some CE wrapper around `uply` that "does task stuff normally, but doesn't in a Blazor build" somehow

**Comment by StachuDotNet** [comment]
Ply seems like it's been last built in .net sdk 3.1.100.
I'm not sure or not if this matters. Assumedly, it _should_, since the .dlls are already formed by the time they get to NuGet? I'm going to try to pull Ply's source (it's small) into my [other repo](https://github.com/StachuDotNet/ply-aot-serialization-bug-repro), rather than using the NuGet package, to see if that changes anything.

**Comment by StachuDotNet** [comment]
@pbiggar some exciting news:

that idea (most recent comment) worked in my separate repo^ !

I'm not sure why. Could be any of:
- built in .net 3.1.100; some bug has been fixed since then
- in a NuGet package, thus separate .dll, and gets handled differently by Blazor somehow
- ?? open to other ideas.

For now, I'm going to create a PR where we drag the code into Dark - it's MIT license so shouldn't an issue.
If that pans out well, I'll create an issue in Ply, and follow up with MSFT folks.

**Comment by StachuDotNet** [comment]
We've gotten a few of these since that^ deploy, but:
- only for one user
- only after they've been on the page for hours

Either the people affected before haven't been hitting ApiServer as much since (maybe they 'gave up'), or they're doing better, and it's legitimately more rare now. I could imagine us building up to the Blazor/wasm/mono memory limits over the course of ~4hr time spans that I've seen the effected user's `client.runtime_ms` be.

To test, I'm checking Honeycomb for all who have faced the error before the recent experiment. If I see that those who have failed before are still hitting ApiServer, without issue, that'll ease my mind a bit. Reducing the problem to one we only encounter when someone's in the Editor hitting analysis a _lot_ is more manageable.

Also, it may be worth adding special info around memory allocation (or something?) to Blazor rollbars. I'm not sure how to query that, but it sounds doable.

**Comment by StachuDotNet** [comment]
I've been able to reproduce, but not really getting more details as to waht's causing the bug.

That said, apparently my Dark tab is taking up... 500+ MB of memory?
![image](https://user-images.githubusercontent.com/906686/172691094-a92d561d-7e8e-4651-ad00-18da9ef5853e.png)

Seeing how I can break that down - maybe the issue really is memory usage after all.

**Comment by StachuDotNet** [comment]
I don't want to connect this issue, but worth considering:
https://github.com/dotnet/runtime/ issues/ 64047

**Comment by StachuDotNet** [comment]
Our of memory concerns, I watched the Chrome task manager while loading my separate test repo's scenario.
Just _loading Blazor_ (without any call to the wasm project there) spikes to 1GB of ram. ???

---

I'm feeling stuck - in Dark, I get the .NET errors of error from .NET, have a feeling that it's related to memory usage, but am not sure how to diagnose from here.

https://user-images.githubusercontent.com/906686/172708633-45d14fd2-ab1d-411d-9b5b-955d88595e1e.mp4

I've been searching around for diagnosing/inspecting memory issues and various things in that space, but either things aren't documented well, or it's all a bit over my head.

This is bothering active users and forces them to either refresh or go away.

I'll take any/all ideas, cc @pbiggar. Could we call in a favor to get a person on the .NET team on a zoom call?

**Comment by StachuDotNet** [comment]
in case the embedded video doesn't work, https://youtu.be/BOFMNjDnvL8

**Comment by StachuDotNet** [comment]
experiment to try: consider using the non-published AOT build. is that still AOT'd? how does it performed?
(in my other repo, the published assets failed while the non-published ones were OK)

**Comment by StachuDotNet** [comment]
Here's a draft of an email to .NET folks.

---

Hi there,

We're currently in production with Blazor - we compile a subset of Dark and use it from the editor for real-time code execution.

This works great normally, but we've been increasingly hitting this error:

```
dotnet.6.0.5.08l2r7srnf.js:1 Uncaught Error: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Remove(Object key)
   at System.Runtime.InteropServices.JavaScript.Runtime.ReleaseJSOwnedObjectByGCHandle(Int32 gcHandle)
    at Object._convert_exception_for_method_call (dotnet.6.0.5.08l2r7srnf.js:1:180229)
    at Object._handle_exception_for_call (dotnet.6.0.5.08l2r7srnf.js:1:182198)
    at Object.managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle [as _release_js_owned_object_by_gc_handle] (managed_BINDINGS_Rel…ectByGCHandle:17:21)
    at Object._js_owned_object_finalized (dotnet.6.0.5.08l2r7srnf.js:1:154018)
    at FinalizationRegistry.cleanupSome (<anonymous>)
_convert_exception_for_method_call	@	dotnet.6.0.5.08l2r7srnf.js:1
_handle_exception_for_call	@	dotnet.6.0.5.08l2r7srnf.js:1
managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle	@	managed_BINDINGS_Rel…ObjectByGCHandle:17
_js_owned_object_finalized	@	dotnet.6.0.5.08l2r7srnf.js:1
```

https://www.youtube.com/watch?v=BOFMNjDnvL8


The error occurs several seconds after our use of Blazor-compiled code is complete.

- we create a binding to a Blazor-compiled method
  `const messageHandler = Module.mono_bind_static_method("[Wasm]Wasm.EvalWorker:OnMessage");`
- we form some request (with a small payload) and call the compiled code
  `messageHandler(data)`
- the `OnMessage` method: deserializes input, computes on that, serializes results, 


We've seen this in all build types (Debug/Release, published/nonpublished, AOT/not AOT).
.NET SDK 6.0.300, latest wasm-tools, Microsoft.AspNetCore.Components.WebAssembly@6.0.3

How can we go about diagnosing the issue here?

**Comment by StachuDotNet** [comment]
not sure or not if it's worth mentioning the memory spikes. Tried to keep it short.

**Comment by StachuDotNet** [comment]
I recompiled blazor.webassembly.js from source today, and `mono_bind_static_method` isn't in it. trying to find what they're using nowadays...

**Comment by StachuDotNet** [comment]
(in case you were thinking to send an email shortly, don't - may have found something)

**Comment by StachuDotNet** [comment]
When I previously tried to run the async code syncro;nously, I did so with `...some task |> Async.AwaitTask |> Async.RunSyncronously`. That failed.

When I now instead try `.Result` instead, it works for me.

Continuing to experiment.

**Comment by StachuDotNet** [comment]
![image](https://user-images.githubusercontent.com/906686/172725608-96e1a811-3210-401f-9dd6-b4fca7ba28c0.png)
forgive me.

**Comment by pbiggar** [comment]
I don't think `.Result` is sinful!

**Comment by pbiggar** [comment]
Still worth reporting the MS folks!

Are we able to go back to using upstream Ply rather than vendoring?

**Comment by StachuDotNet** [comment]
I think so! But I'm going to let things settle for a bit before pinging MSFT or changing anything else there. :)

Following up w/ MSFT is an issue in my private GitHub stuff now!
